# Generated by Django 5.2.17 on 2026-09-04 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_payment_access_used_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(verbose_name='respostas')),
                ('consent_data', models.BooleanField(verbose_name='consentiu com o tratamento dos dados')),
                ('consent_truth', models.BooleanField(verbose_name='confirmou a veracidade')),
                ('consent_version', models.CharField(default='1.0', max_length=20, verbose_name='versão do consentimento')),
                ('consented_at', models.DateTimeField(verbose_name='consentimento registrado em')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anamnesis', to='payments.payment', verbose_name='pagamento')),
            ],
            options={
                'verbose_name': 'anamnese',
                'verbose_name_plural': 'anamneses',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
