# Generated by Django 5.2.17 on 2026-09-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0001_initial'),
        ('payments', '0004_webhookevent_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesis',
            name='consent_data',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='consent_truth',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='consent_version',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='consented_at',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='created_at',
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='form_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='answers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anamnesis', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
