# Generated by Django 5.2.17 on 2026-09-18 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0002_remove_anamnesis_consent_data_and_more'),
        ('customers', '0001_initial'),
        ('payments', '0004_webhookevent_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anamneses', to='customers.customer', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anamnesis', to='payments.payment', verbose_name='pagamento antigo'),
        ),
        migrations.CreateModel(
            name='AnamnesisInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, verbose_name='hash do token')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamnesis_invitations', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anamnesis_invitations', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'convite de anamnese',
                'verbose_name_plural': 'convites de anamnese',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anamnesis', to='anamnesis.anamnesisinvitation', verbose_name='convite'),
        ),
    ]
