# Generated by Django 5.2.17 on 2026-09-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0003_anamnesis_customer_alter_anamnesis_payment_and_more'),
        ('customers', '0002_customer_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesisinvitation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anamnesis_invitations', to='customers.customer'),
        ),
    ]
