# Generated by Django 5.2.17 on 2026-09-03 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='telefone')),
                ('asaas_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID no Asaas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
