# Generated by Django 5.2.17 on 2026-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
