# Generated by Django 5.2.17 on 2026-09-03 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID da cobrança no Asaas')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando pagamento'), ('PAID', 'Pago'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Estornado'), ('FAILED', 'Falhou')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('pix_payload', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code em Base64')),
                ('display_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiração exibida')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('access_token_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do acesso à anamnese')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiração do acesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
