# Generated by Django 5.2.17 on 2026-09-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando pagamento'), ('PAID', 'Pago'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Estornado'), ('FAILED', 'Falhou'), ('PROCESSING', 'Pagamento em processamento')], db_index=True, default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
