# Generated by Django 5.2.17 on 2026-09-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='access_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='acesso utilizado em'),
        ),
    ]
