# Generated by Django 5.2.17 on 2026-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_access_used_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID do evento')),
                ('event_type', models.CharField(max_length=100, verbose_name='tipo do evento')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando pagamento'), ('PROCESSING', 'Pagamento em processamento'), ('PAID', 'Pago'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Estornado'), ('FAILED', 'Falhou')], db_index=True, default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
