# Generated by Django 5.2.17 on 2026-09-21 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=500, verbose_name='resumo')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('cover_image_url', models.URLField(blank=True, max_length=1000, verbose_name='URL da imagem')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado')], db_index=True, default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
